// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      //case TargetPlatform.iOS:
      //return ios;
      //case TargetPlatform.macOS:
      //return macos;
      //case TargetPlatform.windows:
      //return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCbq7EG5OAV6yn6CqhP5vF-zye4xzGNok',
    appId: '1:301551833434:web:795b49f4c48092e7142363',
    messagingSenderId: '301551833434',
    projectId: 'natis-8c09a',
    authDomain: 'natis-8c09a.firebaseapp.com',
    storageBucket: 'natis-8c09a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaTKpgOdLQox7XYXWNaoiMXCXQ-MPiCCs',
    appId: '1:301551833434:android:38715bacea3602d9142363',
    messagingSenderId: '301551833434',
    projectId: 'natis-8c09a',
    storageBucket: 'natis-8c09a.firebasestorage.app',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyAj7ZC-kquebZAAPP9d8azrBMOjnFiTBRY',
  //   appId: '1:301551833434:ios:6ad446c666cd968c142363',
  //   messagingSenderId: '301551833434',
  //   projectId: 'natis-8c09a',
  //   storageBucket: 'natis-8c09a.firebasestorage.app',
  //   iosClientId: '301551833434-n3m5uubhhcb9ea8bbrakrt7ugfqb1dpv.apps.googleusercontent.com',
  //   iosBundleId: 'com.example.frontend',
  // );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyAj7ZC-kquebZAAPP9d8azrBMOjnFiTBRY',
  //   appId: '1:301551833434:ios:6ad446c666cd968c142363',
  //   messagingSenderId: '301551833434',
  //   projectId: 'natis-8c09a',
  //   storageBucket: 'natis-8c09a.firebasestorage.app',
  //   iosClientId: '301551833434-n3m5uubhhcb9ea8bbrakrt7ugfqb1dpv.apps.googleusercontent.com',
  //   iosBundleId: 'com.example.frontend',
  // );

  // static const FirebaseOptions windows = FirebaseOptions(
  //   apiKey: 'AIzaSyDCbq7EG5OAV6yn6CqhP5vF-zye4xzGNok',
  //   appId: '1:301551833434:web:a6171d2c3b7adff4142363',
  //   messagingSenderId: '301551833434',
  //   projectId: 'natis-8c09a',
  //   authDomain: 'natis-8c09a.firebaseapp.com',
  //   storageBucket: 'natis-8c09a.firebasestorage.app',
  // );
}